name: Create Release

on:
  push:
    tags:
      - "*.*.*"
      - "*.*.*-beta*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create temporary directory
        run: mkdir temp
      - name: Copy files to temporary directory
        run: rsync -av --exclude=temp/ --exclude=zipfolders.sh . temp/
      - name: Create zip file
        run: |
          cd temp/
          7z a ../dude_where_is_my_gear_v${{ env.VERSION }}.zip *
        env:
          VERSION: ${{ github.ref_name }}
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "dude_where_is_my_gear_v${{ github.ref_name }}.zip"
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ secrets.GITHUB_TOKEN }}
