name: Create Release

on:
  push:
    tags:
      - "*.*.*"
      - "*.*.*-beta*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create temporary directory
        run: mkdir temp
      - name: Copy files to temporary directory
        run: rsync -av --exclude=temp/ --exclude=zipfolders.sh . temp/
      - name: Create zip file
        run: |
          cd temp/
          7z a ../dude_where_is_my_gear_v${{ env.VERSION }}.zip *
        env:
          VERSION: ${{ github.ref_name }}
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          includeInvalidCommits: true
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ github.ref_name }}
          artifacts: "dude_where_is_my_gear_v${{ github.ref_name }}.zip"
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ steps.extract_branch.outputs.branch }}
          commit_message: "docs: update CHANGELOG.md for ${{ steps.extract_branch.outputs.branch }} [skip ci]"
          file_pattern: CHANGELOG.md
